[workspace]
resolver = "2"
members = [
    "common",
    "day_1",
    "day_2",
    "day_3",
    "day_4",
    "day_5",
    "day_6",
    "day_7",
    "day_8",
    "day_9",
    "day_10",
    "day_11",
    "day_12",
    "day_13",
    "template",
]

[workspace.package]
version = "0.1.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2021"
publish = false

[workspace.dependencies]
anyhow = "1"
common = { path = "common" }
