[workspace]
resolver = "2"
members = [
    "common",
    "day_1",
    "template",
]

[workspace.package]
version = "0.1.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2021"
publish = false

[workspace.dependencies]
anyhow = "1"
common = { path = "common" }
